run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - typecheck
    - gosimple
    - goimports
    - gofmt
    - bodyclose
    - gocritic
    - nilerr
    - makezero
    - unconvert
    - nolintlint

issues:
  exclude-use-default: false
