lint:
	golangci-lint run ./core/... ./serverkit/... ./cachekit/... ./databasekit/...

lint-fix:
	golangci-lint run --fix ./core/... ./serverkit/... ./cachekit/... ./databasekit/...

fmt:
	golangci-lint fmt ./core/... ./serverkit/... ./cachekit/... ./databasekit/...
