lint:
	golangci-lint run ./core/... ./serverkit/... ./cachekit/... ./databasekit/... ./workerkit/...

lint-fix:
	golangci-lint run --fix ./core/... ./serverkit/... ./cachekit/... ./databasekit/... ./workerkit/...

fmt:
	golangci-lint fmt ./core/... ./serverkit/... ./cachekit/... ./databasekit/... ./workerkit/...
